# Welcome to Numpy

In [1]:
import numpy as np

# Array Creation : Conversion from other python structures

In [2]:
single_dimensional_arr = np.array([1,2,3], np.int32)

In [3]:
single_dimensional_arr

array([1, 2, 3], dtype=int32)

In [4]:
single_dimensional_arr[1]

np.int32(2)

In [5]:
two_dimensional_array = np.array([[3,6,9,12],[2,4,6,8], [4,8,12,16]])

In [6]:
two_dimensional_array

array([[ 3,  6,  9, 12],
       [ 2,  4,  6,  8],
       [ 4,  8, 12, 16]])

In [7]:
two_dimensional_array[2, 3]

np.int64(16)

In [8]:
two_dimensional_array.shape

(3, 4)

In [9]:
two_dimensional_array.dtype

dtype('int64')

In [10]:
two_dimensional_array.size

12

# Intrinsic NumPy array creation functions

In [11]:
zero_arr = np.zeros((2,5))

In [12]:
zero_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
zero_arr.dtype

dtype('float64')

In [14]:
zero_arr.shape

(2, 5)

In [15]:
zero_arr.size

10

 ** Using arange - generates arrays with evenly spaced values within a defined interval **

In [16]:
rng = np.arange(15)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

** Using linspace - it generates an array of evenly spaced numbers over a defined interval **

In [18]:
linspace = np.linspace(1,5,4)

In [19]:
linspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

 ** empty() - it is used to create a new array of given shape and type, without initializing entries **

In [20]:
empty_arr = np.empty((2,3))

In [21]:
empty_arr

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.06810268e-306, 1.89146896e-307, 7.56571288e-307]])

In [22]:
ide = np.identity(45)

In [23]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [24]:
ide.shape

(45, 45)

** reshape means changing the shape of an array. **

In [25]:
# reshape_arr = rng.reshape(3,4)

In [26]:
reshape_arr = rng.reshape(3,5)

In [27]:
reshape_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
reshape_arr.shape

(3, 5)

** ravel() provide a flattened view of a multi-dimensional array **

In [29]:
reshape_arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [31]:
axis_arr = np.array(x)

In [32]:
print(axis_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
axis_arr.sum(axis=0) # this sums the col

array([12, 15, 18])

In [34]:
axis_arr.sum(axis=1) # this sums the rows

array([ 6, 15, 24])

In [35]:
for item in axis_arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


** Difference in size **

In [36]:
import sys

In [37]:
py_arr = [1,2,3,55]

In [38]:
np_arr = np.array(py_arr)

In [39]:
sys.getsizeof(1)*len(py_arr)

112

In [40]:
np_arr.itemsize * np_arr.size

32